### ISSUE TITLE
TypeError: 'MeetupObject' object is not iterable

### ISSUE THREAD

**Issue by rmoff** [mattj-io/query_meetup#3]
Hi Matt! This was working great for me, and is so useful. But, 'something' has changed in the last few months since running it, and now it errors out: 

```
$ python -V
Python 2.7.10
$ python query_meetup.py --config ../config.yml
City: Paris Country: FR
29/30 (10 seconds remaining)
Traceback (most recent call last):
  File "query_meetup.py", line 334, in <module>
    main()
  File "query_meetup.py", line 299, in main
    res += meetup_query.search_via_api(city, country)
TypeError: 'MeetupObject' object is not iterable
```

any ideas?

**Comment by mattj-io** [comment]
Sorry @rmoff - for some reason I'm not getting notifications from this repo. I'm on the road at the minute, but will check this out once I'm back at home next week

**Comment by mattj-io** [comment]
Apologies, I finally got round to looking at this. That error will be me not handling something in the returned data, I can't repeat it with my config files - if you're still seeing it, could you share your config so I can check the returned data ?
